language: generic

# Build PDF using texlive and pdflatex
install:
  - source ./bin/install_texlive.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  - ./bin/build.sh paper
deploy:
  skip_cleanup: true
  provider: script
  script: ./bin/travis-push.sh paper.pdf
  on:
    all_branches: true
