language: generic

# Build PDF using texlive and pdflatex
install:
  - source ./bin/install_texlive.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  - source ./bin/build.sh paper ActorDB.pdf
after_success:
  - source ./bin/travis-push.sh ActorDB.pdf
